#!/bin/sh
bl_dev=/sys/class/backlight/intel_backlight
step=25

case $1 in
  -) echo $(($(< $bl_dev/brightness) - $step)) | sudo tee $bl_dev/brightness;;
  +) echo $(($(< $bl_dev/brightness) + $step)) | sudo tee $bl_dev/brightness;;
esac
