#!/bin/bash

# ❌
OFF="\u274C"

# 
WIFI=""

# 
#ON="\uf293"

# 
ON="\uf00c"
STATUS=$(rfkill -n --output soft list wlan | head -n 1)
ask(){
    CHOICE=$(echo -e "on\noff" | rofi -dmenu -no-fullscreen -eh 1 -width -14 -bw 2 -m -3 -no-custom -theme-str '#window {anchor:southeast; location: northwest;}' -font "Fira Mono 12" -hide-scrollbar -p "WiFi on/off" -lines 2 )
}

print_on(){
    echo -e "$WIFI $ON"
    echo -e "$ON"
    exit
}

print_off(){
    echo -e "$WIFI $OFF"
    echo -e "$OFF"
    exit
}

print_status(){
    case "${STATUS}" in
        "unblocked")
            echo -e "$WIFI $ON"
            echo -e "$ON"
            echo "" ;;
        "blocked")
            echo -e "$WIFI $OFF"
            echo -e "$OFF"
            echo "" ;;
        *)
            echo "fail"
    esac

}

set_wifi(){
    if [[ "${CHOICE}" == "off" ]]; then
        rfkill block wlan
        print_off
    else
        rfkill unblock wlan
        print_on
    fi
}

toggle(){
    if [[ "${STATUS}" == "unblocked" ]]; then
        CHOICE="off"
    else
        CHOICE="on"
    fi
    set_wifi
}

case "${BLOCK_BUTTON}" in
    1|3)
        ask
        set_wifi
        ;;
    2)
        toggle
        ;;
    *)
        print_status
        ;;
esac

