#!/bin/bash
isoname="${1}"
GRUBCFG="$HOME/build/grub-refind/boot/grub/${isoname}.cfg"
DEVICEPATH=$(df --output=source,target | grep "${2}" | awk '{print $2}')
MODULES="ext2 part_gpt part_msdos"
#needed standard modules
#use to strip down size
#MODULES+="acpi ahci ata bufio disk fat file font linux "
echo 'configfile ${cmdpath}/helper.cfg' > /tmp/grub.cfg
grub-mkstandalone -d /usr/lib/grub/x86_64-efi/ \
                  -O x86_64-efi \
                  -o "${DEVICEPATH}"/boot/grub/mbusb.d/${isoname}.d/$isoname.efi \
                  --modules="${MODULES}" \
                  --locales="en@quot de" \
                  --compress="xz" \
                  "boot/grub/grub.cfg=/tmp/grub.cfg"

